<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTmjcemo\EccubeProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTmjcemo/EccubeProdProjectContainer.php') {
    touch(__DIR__.'/ContainerTmjcemo.legacy');

    return;
}

if (!\class_exists(EccubeProdProjectContainer::class, false)) {
    \class_alias(\ContainerTmjcemo\EccubeProdProjectContainer::class, EccubeProdProjectContainer::class, false);
}

return new \ContainerTmjcemo\EccubeProdProjectContainer([
    'container.build_hash' => 'Tmjcemo',
    'container.build_id' => 'b6b5dfe8',
    'container.build_time' => 1604055483,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTmjcemo');
